server:
  port: 7070

cloud:
  aws:
    credentials:
      access-key: test
      secret-key: test
    sqs:
      endpoint: http://localhost:4566
      queues:
        interventions-events: delius-intervention-events-queue
