server:
  port: 7070

spring:
  security:
    oauth2:
      client:
        registration:
          interventions-client:
            client-id: interventions
            client-secret: clientsecret
          community-api-client:
            client-id: community-api-client
            client-secret: community-api-client

cloud:
  aws:
    credentials:
      access-key: test
      secret-key: test
    sqs:
      endpoint: http://localhost:4566
      queues:
        interventions-events: delius-intervention-events-queue

services:
  hmpps-auth:
    baseurl: http://hmpps-auth:8090/auth
  interventions-api:
    baseurl: http://localhost:8080
  community-api:
    baseurl: http://localhost:8091