server:
  port: 7070

spring:
  security:
    oauth2:
      client:
        registration:
          interventions-event-client:
            client-id: interventions
            client-secret: clientsecret

hmpps.sqs:
  region: eu-west-2
  localstackUrl: http://localhost:4566
  provider: localstack
  queues:
    deliusinterventionseventsqueue:
      queueName:  delius-interventions-events-queue
      dlqName: delius-interventions-events-dlq
      subscribeTopicId: interventioneventstopic
      subscribeFilter: '{"eventType":[ { "prefix": "intervention." } ] }'
  topics:
    interventioneventstopic:
      arn: arn:aws:sns:${hmpps.sqs.region}:000000000000:intervention-events-local

services:
  hmpps-auth:
    baseurl: http://hmpps-auth:8090/auth
  interventions-api:
    baseurl: http://localhost:8080
  community-api:
    baseurl: http://localhost:8091

interventions-ui:
  baseurl: http://localhost:3000

features:
  crs:
    notify-action-plan-submitted: true
    notify-action-plan-approved: true