info.app:
  name: Hmpps Delius Interventions Event Listener
  version: 1.0

spring:
  main:
    banner-mode: off
  application:
    name: hmpps-delius-interventions-event-listener
  codec:
    max-in-memory-size: 10MB
  security:
    oauth2:
      client:
        provider:
          hmpps-auth:
            token-uri: ${services.hmpps-auth.baseurl}/oauth/token
        registration:
          interventions-client:
            provider: hmpps-auth
            authorization-grant-type: client_credentials
            scope: read,write
          community-api-client:
            provider: hmpps-auth
            authorization-grant-type: client_credentials
            scope: read
      resourceserver:
        jwt:
          issuer-uri: ${services.hmpps-auth.baseurl}/issuer
          jwk-set-uri: ${services.hmpps-auth.baseurl}/.well-known/jwks.json

server:
  port: 8080
  servlet:
    context-path: /
  forward-headers-strategy: native
  tomcat:
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto
      internal-proxies: 10\.\d{1,3}\.\d{1,3}\.\d{1,3}|192\.168\.\d{1,3}\.\d{1,3}|169\.254\.\d{1,3}\.\d{1,3}|127\.\d{1,3}\.\d{1,3}\.\d{1,3}|172\.1[6-9]{1}\.\d{1,3}\.\d{1,3}|172\.2[0-9]{1}\.\d{1,3}\.\d{1,3}|172\.3[0-1]{1}\.\d{1,3}\.\d{1,3}|0:0:0:0:0:0:0:1|::1|100\.6[4-9]\.\d{1,3}\.\d{1,3}|100\.[7-9][0-9]{1}\.\d{1,3}\.\d{1,3}|100\.1[0-1][0-9]{1}\.\d{1,3}\.\d{1,3}|100\.12[0-7]\.\d{1,3}\.\d{1,3}
  shutdown: graceful
  error:
    include-message: always

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: 'info, health'
  endpoint:
    health:
      cache:
        time-to-live: 2000ms
      show-components: always
      show-details: always
      probes:
        enabled: true
    info:
      cache:
        time-to-live: 2000ms

hmpps.sqs:
  region: eu-west-2

services:
  interventions-api:
    connect-timeout-seconds: 30
    read-timeout-seconds: 5
    write-timeout-seconds: 5
  community-api:
    connect-timeout-seconds: 30
    read-timeout-seconds: 10
    write-timeout-seconds: 10

# all features should be disabled by default and enabled per-environment
features:
  crs:
    notify-action-plan-submitted: false

interventions-ui:
  locations:
    probation-practitioner:
      action-plan: "/probation-practitioner/referrals/{id}/action-plan"
